# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'
  packageVersion: '0.0.$(Build.BuildNumber)'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  failOnStderr: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-pack.OctopusPack@3
  displayName: 'Package for Octopus Deploy'
  inputs:
    PackageId: Azure.DevOps.Test
    PackageVersion: '$(packageVersion)'
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    OutputPath: '$(Build.ArtifactStagingDirectory)'

- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-push.OctopusPush@3
  displayName: 'Push Package to Octopus'
  inputs:
    OctoConnectedServiceName: 'Octopus Deploy'
    Package: '$(Build.ArtifactStagingDirectory)\Azure.DevOps.Test.$(packageVersion).nupkg'



